function dlift = jacobianLift_poly1(in1)
%JACOBIANLIFT_POLY1
%    DLIFT = JACOBIANLIFT_POLY1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    22-Jan-2019 12:02:08

dlift = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[8,2]);
