function dlift = jacobianLift_poly2(in1)
%JACOBIANLIFT_POLY2
%    DLIFT = JACOBIANLIFT_POLY2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    16-Apr-2019 12:32:45

ud1 = in1(5,:);
ud2 = in1(6,:);
ud3 = in1(7,:);
x1 = in1(1,:);
x2 = in1(2,:);
xd1 = in1(3,:);
xd2 = in1(4,:);
dlift = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,x1.*2.0,x2,0.0,xd1,0.0,0.0,xd2,0.0,0.0,0.0,ud1,0.0,0.0,0.0,0.0,ud2,0.0,0.0,0.0,0.0,0.0,ud3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,x1,x2.*2.0,0.0,xd1,0.0,0.0,xd2,0.0,0.0,0.0,ud1,0.0,0.0,0.0,0.0,ud2,0.0,0.0,0.0,0.0,0.0,ud3,0.0,0.0,0.0,0.0,0.0,0.0],[36,2]);
