function polyBasis = stateLift_poly2(in1)
%STATELIFT_POLY2
%    POLYBASIS = STATELIFT_POLY2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    21-Jan-2019 17:16:07

ud1 = in1(5,:);
ud2 = in1(6,:);
ud3 = in1(7,:);
x1 = in1(1,:);
x2 = in1(2,:);
xd1 = in1(3,:);
xd2 = in1(4,:);
polyBasis = [x1;x2;xd1;xd2;ud1;ud2;ud3;x1.^2;x1.*x2;x2.^2;x1.*xd1;x2.*xd1;xd1.^2;x1.*xd2;x2.*xd2;xd1.*xd2;xd2.^2;ud1.*x1;ud1.*x2;ud1.*xd1;ud1.*xd2;ud1.^2;ud2.*x1;ud2.*x2;ud2.*xd1;ud2.*xd2;ud1.*ud2;ud2.^2;ud3.*x1;ud3.*x2;ud3.*xd1;ud3.*xd2;ud1.*ud3;ud2.*ud3;ud3.^2;1.0];
