function polyBasis = stateLift_poly1(in1)
%STATELIFT_POLY1
%    POLYBASIS = STATELIFT_POLY1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    19-Dec-2018 17:36:03

ud1 = in1(5,:);
ud2 = in1(6,:);
ud3 = in1(7,:);
x1 = in1(1,:);
x2 = in1(2,:);
xd1 = in1(3,:);
xd2 = in1(4,:);
polyBasis = [x1;x2;xd1;xd2;ud1;ud2;ud3;1.0];
