function fourierBasis = stateLift_fourier_sparser2(in1)
%STATELIFT_FOURIER_SPARSER2
%    FOURIERBASIS = STATELIFT_FOURIER_SPARSER2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    22-Jan-2019 12:22:09

ud1 = in1(5,:);
ud2 = in1(6,:);
ud3 = in1(7,:);
x1 = in1(1,:);
x2 = in1(2,:);
xd1 = in1(3,:);
xd2 = in1(4,:);
t2 = x1.*pi.*2.0;
t3 = x2.*pi.*2.0;
t4 = xd1.*pi.*2.0;
t5 = xd2.*pi.*2.0;
t6 = ud1.*pi.*2.0;
t7 = ud2.*pi.*2.0;
t8 = ud3.*pi.*2.0;
t9 = sin(t2);
t10 = sin(t3);
t11 = sin(t4);
t12 = sin(t5);
t13 = sin(t6);
t14 = sin(t7);
t15 = sin(t8);
t16 = cos(t2);
t17 = x1.*pi.*4.0;
t18 = cos(t3);
t19 = x2.*pi.*4.0;
t20 = cos(t4);
t21 = xd1.*pi.*4.0;
t22 = cos(t5);
t23 = xd2.*pi.*4.0;
t24 = cos(t6);
t25 = ud1.*pi.*4.0;
t26 = cos(t7);
t27 = ud2.*pi.*4.0;
t28 = cos(t8);
t29 = ud3.*pi.*4.0;
fourierBasis = [x1;x2;xd1;xd2;ud1;ud2;ud3;1.0;t9;t10;t11;t12;t13;t14;t15;t16;t18;t20;t22;t24;t26;t28;sin(t17);t9.*t10;sin(t19);t9.*t11;t10.*t11;sin(t21);t9.*t12;t10.*t12;t11.*t12;sin(t23);t9.*t13;t10.*t13;t11.*t13;t12.*t13;sin(t25);t9.*t14;t10.*t14;t11.*t14;t12.*t14;t13.*t14;sin(t27);t9.*t15;t10.*t15;t11.*t15;t12.*t15;t13.*t15;t14.*t15;sin(t29);t9.*t16;t10.*t16;t11.*t16;t12.*t16;t13.*t16;t14.*t16;t15.*t16;cos(t17);t9.*t18;t10.*t18;t11.*t18;t12.*t18;t13.*t18;t14.*t18;t15.*t18;t16.*t18;cos(t19);t9.*t20;t10.*t20;t11.*t20;t12.*t20;t13.*t20;t14.*t20;t15.*t20;t16.*t20;t18.*t20;cos(t21);t9.*t22;t10.*t22;t11.*t22;t12.*t22;t13.*t22;t14.*t22;t15.*t22;t16.*t22;t18.*t22;t20.*t22;cos(t23);t9.*t24;t10.*t24;t11.*t24;t12.*t24;t13.*t24;t14.*t24;t15.*t24;t16.*t24;t18.*t24;t20.*t24;t22.*t24;cos(t25);t9.*t26;t10.*t26;t11.*t26;t12.*t26;t13.*t26;t14.*t26;t15.*t26;t16.*t26;t18.*t26;t20.*t26;t22.*t26;t24.*t26;cos(t27);t9.*t28;t10.*t28;t11.*t28;t12.*t28;t13.*t28;t14.*t28;t15.*t28;t16.*t28;t18.*t28;t20.*t28;t22.*t28;t24.*t28;t26.*t28;cos(t29)];
