function fourierBasis = stateLift_fourier_sparser1(in1)
%STATELIFT_FOURIER_SPARSER1
%    FOURIERBASIS = STATELIFT_FOURIER_SPARSER1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    22-Jan-2019 12:19:13

ud1 = in1(5,:);
ud2 = in1(6,:);
ud3 = in1(7,:);
x1 = in1(1,:);
x2 = in1(2,:);
xd1 = in1(3,:);
xd2 = in1(4,:);
t2 = x1.*pi.*2.0;
t3 = x2.*pi.*2.0;
t4 = xd1.*pi.*2.0;
t5 = xd2.*pi.*2.0;
t6 = ud1.*pi.*2.0;
t7 = ud2.*pi.*2.0;
t8 = ud3.*pi.*2.0;
fourierBasis = [x1;x2;xd1;xd2;ud1;ud2;ud3;1.0;sin(t2);sin(t3);sin(t4);sin(t5);sin(t6);sin(t7);sin(t8);cos(t2);cos(t3);cos(t4);cos(t5);cos(t6);cos(t7);cos(t8)];
